<?php
if (!defined('ABSPATH')) exit;
?>
<div class="wrap cc-outreach-wrap">
    <h1><span class="dashicons dashicons-book-alt"></span> Documentation, Tutorials & Growth Blueprint</h1>
    <p>Complete guide to configuring CloseClient Outreach, automating client acquisition, setting up Google Sheets write-back webhooks, and executing the Agency Growth Blueprint.</p>

    <!-- Tab Navigation -->
    <h2 class="nav-tab-wrapper">
        <a href="#tab-quickstart" class="nav-tab nav-tab-active">Quick Start Guide</a>
        <a href="#tab-sheets" class="nav-tab">Google Sheets Write-Back Setup</a>
        <a href="#tab-ai-prompts" class="nav-tab">AI Prompts & Customization</a>
        <a href="#tab-blueprint" class="nav-tab">Agency Growth Blueprint</a>
    </h2>

    <!-- Section 1: Quick Start Guide -->
    <div class="cc-card" style="margin-top:20px;">
        <h2><span class="dashicons dashicons-flag"></span> 1. Quick Start Tutorial</h2>
        <ol style="line-height:1.8; font-size:14px;">
            <li><strong>Configure API Keys:</strong> Go to <a href="<?php echo admin_url('admin.php?page=closeclient-outreach-settings'); ?>">Settings</a> and enter your OpenAI API key (<code>sk-...</code>) or Anthropic API key (<code>sk-ant-...</code>). API keys are automatically encrypted at rest using AES-256-CBC.</li>
            <li><strong>Set Up Outreach Mode:</strong> Choose between <em>Draft Mode</em> (manual review), <em>Approval Queue Mode</em>, or <em>Automated Sending Mode</em>. We strongly recommend <strong>Draft Mode</strong> when starting to inspect every personalized outreach draft.</li>
            <li><strong>Find Prospects:</strong> Use the <a href="<?php echo admin_url('admin.php?page=closeclient-outreach-prospecting'); ?>">Find Leads</a> screen to search for coaches or consultants in specific industries (e.g., Executive Coach, Marketing Consultant) and target locations.</li>
            <li><strong>Review & Send:</strong> Go to <a href="<?php echo admin_url('admin.php?page=closeclient-outreach-queue'); ?>">Outreach Queue</a> to inspect AI-generated personalized drafts. Edit or approve them with one click.</li>
        </ol>
    </div>

    <!-- Section 2: Google Sheets Webhook Apps Script -->
    <div class="cc-card">
        <h2><span class="dashicons dashicons-google"></span> 2. Google Sheets Two-Way Apps Script Setup</h2>
        <p>To enable <strong>automatic write-back</strong> from WordPress to your Google Sheet whenever a prospect replies or changes status, paste the following script into your Google Sheet's <em>Extensions > Apps Script</em> editor and deploy as a Web App:</p>

        <textarea class="widefat" rows="14" readonly style="font-family:monospace; background:#f6f8fa; padding:10px;">
function doPost(e) {
  try {
    var data = JSON.parse(e.postData.contents);
    var sheet = SpreadsheetApp.getActiveSpreadsheet().getSheetByName("Leads");
    if (!sheet) sheet = SpreadsheetApp.getActiveSpreadsheet().getSheets()[0];

    var email = data.email;
    var status = data.status;
    var summary = data.conversation_summary || "";

    var values = sheet.getDataRange().getValues();
    var emailCol = 4; // Column E (index 4) by default

    for (var i = 1; i < values.length; i++) {
      if (values[i][emailCol] == email) {
        sheet.getRange(i + 1, 11).setValue(status); // Update Status Column
        if (summary) sheet.getRange(i + 1, 16).setValue(summary); // Update Summary Column
        return ContentService.createTextOutput(JSON.stringify({result: "success"})).setMimeType(ContentService.MimeType.JSON);
      }
    }
    return ContentService.createTextOutput(JSON.stringify({result: "email_not_found"})).setMimeType(ContentService.MimeType.JSON);
  } catch (err) {
    return ContentService.createTextOutput(JSON.stringify({result: "error", error: err.toString()})).setMimeType(ContentService.MimeType.JSON);
  }
}
</textarea>
        <p class="description">Copy the Web App URL generated by Google Apps Script and paste it into the <strong>Google Apps Script Webhook (Write-Back)</strong> field in Settings.</p>
    </div>

    <!-- Section 3: AI Prompts & Best Practices -->
    <div class="cc-card">
        <h2><span class="dashicons dashicons-lightbulb"></span> 3. Personalized Outreach Prompting Rules</h2>
        <ul style="line-height:1.8; font-size:14px;">
            <li><strong>Relevance over Volume:</strong> Target coaches/consultants who actively generate business through their website. Never send generic "Dear Sir/Madam" templates.</li>
            <li><strong>Specific Value Hooks:</strong> Highlight speed, mobile conversion rate, or clear booking funnels (e.g. Calendly / Acuity integrations).</li>
            <li><strong>Short & Conversational:</strong> Emails under 125 words yield a 300% higher response rate than long proposal pitches.</li>
        </ul>
    </div>

    <!-- Section 4: CloseClient Growth Blueprint -->
    <div class="cc-card" style="border-left: 4px solid #28a745; background: #f8fff9;">
        <h2 style="color:#28a745;"><span class="dashicons dashicons-chart-line"></span> 4. CloseClient Web Dev Agency Growth Blueprint</h2>
        <h3>Target Market Focus: Coaches & Consultants</h3>
        <p>Business coaches, executive coaches, and consultants heavily rely on high-converting websites to establish credibility and convert traffic into 5-figure coaching retainers.</p>

        <h3>3-Step Client Acquisition Funnel:</h3>
        <ol style="line-height:1.8;">
            <li><strong>Step 1: Permission-First Outreach:</strong> Send a short 3-sentence personalized email noticing a specific improvement area on their current website (e.g., slow mobile load time or lack of clear call-to-action).</li>
            <li><strong>Step 2: 5-Minute Video Website Breakdown:</strong> When they reply with interest, record a 3-minute Loom video walking through 3 specific fixes that will double their client consultation bookings.</li>
            <li><strong>Step 3: Close Development Retainer:</strong> Offer a turnkey WordPress Website Redesign package ($3,000 - $7,500) paired with an ongoing monthly maintenance & lead engine retainer ($500/mo).</li>
        </ol>
    </div>
</div>
